// Единая подложка стран для ОБОИХ режимов поиска (задача 2026-08-03: были два
// независимых, несинхронизированных списка — 80 вручную отобранных стран для
// Scopus-режима (SCOPUS_COUNTRIES) и произвольные значения statsStore.by_country
// в catalog-режиме, для которых словари переводов не гарантированно совпадали).
//
// Источник — ISO 3166-1 (все 249 официально присвоенных кодов) + XK (Косово,
// общепринятый user-assigned код вне формального ISO 3166-1, но фактически
// используемый везде, включая многие базы аффилиаций) — итого 250, через пакет
// i18n-iso-countries (CLDR). EN-значение — то, что реально уходит в Scopus CQL
// (AFFILCOUNTRY(...), app/infrastructure/scopus_client.py) и хранится как
// affiliation_country в каталоге, поэтому для стран, уже присутствовавших в
// прежнем списке из 80, значение сохранено БУКВАЛЬНО прежним, а не заменено на
// «официальное» имя из пакета — у части стран пакет по умолчанию отдаёт
// формальное/договорное имя вместо разговорного (Russia -> Russian Federation,
// United States -> United States of America, Turkey -> Türkiye, Taiwan ->
// Taiwan, Province of China) — не то, что использует Scopus и уже накопленные
// данные каталога; замена молча сломала бы поиск/фильтр по этим странам.
// Для НОВЫХ стран (не входивших в прежние 80) выбрано общеупотребимое короткое
// имя (пакетный alias при формальном official, либо ручной override — CD/CG
// намеренно оставлены полными названиями, иначе оба получили бы одинаковый alias
// «Congo»; KP/EH/MO — пакетные RU-варианты были аббревиатурой/полной формулой
// без сокращённого альтернативного варианта, заменены на обычные короткие имена).
//
// sr-Latn (используется как ресурс для локали cnr/Montenegrin по всему сайту —
// см. frontend/CLAUDE.md, «URL architecture») — для новых стран получено
// детерминированной транслитерацией сербской кириллицы (пакетные sr-данные) в
// латиницу по стандартной сербской диграфной таблице (не приближение — сербская
// кириллица имеет ровно один канонический латинский эквивалент).

export const ALL_COUNTRIES = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthélemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export type Country = (typeof ALL_COUNTRIES)[number];

export const COUNTRY_TRANSLATIONS_RU: Record<string, string> = {
  "Afghanistan": "Афганистан",
  "Åland Islands": "Аландские острова",
  "Albania": "Албания",
  "Algeria": "Алжир",
  "American Samoa": "Американское Самоа",
  "Andorra": "Андорра",
  "Angola": "Ангола",
  "Anguilla": "Ангилья",
  "Antarctica": "Антарктида",
  "Antigua and Barbuda": "Антигуа и Барбуда",
  "Argentina": "Аргентина",
  "Armenia": "Армения",
  "Aruba": "Аруба",
  "Australia": "Австралия",
  "Austria": "Австрия",
  "Azerbaijan": "Азербайджан",
  "Bahamas": "Багамы",
  "Bahrain": "Бахрейн",
  "Bangladesh": "Бангладеш",
  "Barbados": "Барбадос",
  "Belarus": "Беларусь",
  "Belgium": "Бельгия",
  "Belize": "Белиз",
  "Benin": "Бенин",
  "Bermuda": "Бермуды",
  "Bhutan": "Бутан",
  "Bolivia": "Боливия",
  "Bonaire, Sint Eustatius and Saba": "Бонэйр, Синт-Эстатиус и Саба",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  "Botswana": "Ботсвана",
  "Bouvet Island": "Остров Буве",
  "Brazil": "Бразилия",
  "British Indian Ocean Territory": "Британская территория в Индийском океане",
  "Brunei": "Бруней",
  "Bulgaria": "Болгария",
  "Burkina Faso": "Буркина-Фасо",
  "Burundi": "Бурунди",
  "Cambodia": "Камбоджа",
  "Cameroon": "Камерун",
  "Canada": "Канада",
  "Cape Verde": "Кабо-Верде",
  "Cayman Islands": "Острова Кайман",
  "Central African Republic": "Центральноафриканская Республика",
  "Chad": "Чад",
  "Chile": "Чили",
  "China": "Китай",
  "Christmas Island": "Остров Рождества",
  "Cocos (Keeling) Islands": "Кокосовые острова",
  "Colombia": "Колумбия",
  "Comoros": "Коморы",
  "Cook Islands": "Острова Кука",
  "Costa Rica": "Коста-Рика",
  "Cote d'Ivoire": "Кот-д’Ивуар",
  "Croatia": "Хорватия",
  "Cuba": "Куба",
  "Curaçao": "Кюрасао",
  "Cyprus": "Кипр",
  "Czech Republic": "Чехия",
  "Democratic Republic of the Congo": "Демократическая Республика Конго",
  "Denmark": "Дания",
  "Djibouti": "Джибути",
  "Dominica": "Доминика",
  "Dominican Republic": "Доминиканская Республика",
  "Ecuador": "Эквадор",
  "Egypt": "Египет",
  "El Salvador": "Сальвадор",
  "Equatorial Guinea": "Экваториальная Гвинея",
  "Eritrea": "Эритрея",
  "Estonia": "Эстония",
  "Eswatini": "Эсватини",
  "Ethiopia": "Эфиопия",
  "Falkland Islands (Malvinas)": "Фолклендские острова",
  "Faroe Islands": "Фареры",
  "Fiji": "Фиджи",
  "Finland": "Финляндия",
  "France": "Франция",
  "French Guiana": "Гвиана",
  "French Polynesia": "Французская Полинезия",
  "French Southern Territories": "Французские Южные и Антарктические Территории",
  "Gabon": "Габон",
  "Gambia": "Гамбия",
  "Georgia": "Грузия",
  "Germany": "Германия",
  "Ghana": "Гана",
  "Gibraltar": "Гибралтар",
  "Greece": "Греция",
  "Greenland": "Гренландия",
  "Grenada": "Гренада",
  "Guadeloupe": "Гваделупа",
  "Guam": "Гуам",
  "Guatemala": "Гватемала",
  "Guernsey": "Гернси",
  "Guinea": "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  "Guyana": "Гайана",
  "Haiti": "Гаити",
  "Heard Island and McDonald Islands": "Херд и Макдональд",
  "Holy See (Vatican City State)": "Ватикан",
  "Honduras": "Гондурас",
  "Hong Kong": "Гонконг",
  "Hungary": "Венгрия",
  "Iceland": "Исландия",
  "India": "Индия",
  "Indonesia": "Индонезия",
  "Iran": "Иран",
  "Iraq": "Ирак",
  "Ireland": "Ирландия",
  "Isle of Man": "Остров Мэн",
  "Israel": "Израиль",
  "Italy": "Италия",
  "Jamaica": "Ямайка",
  "Japan": "Япония",
  "Jersey": "Джерси",
  "Jordan": "Иордания",
  "Kazakhstan": "Казахстан",
  "Kenya": "Кения",
  "Kiribati": "Кирибати",
  "Kosovo": "Косово",
  "Kuwait": "Кувейт",
  "Kyrgyzstan": "Киргизия",
  "Laos": "Лаос",
  "Latvia": "Латвия",
  "Lebanon": "Ливан",
  "Lesotho": "Лесото",
  "Liberia": "Либерия",
  "Libya": "Ливия",
  "Liechtenstein": "Лихтенштейн",
  "Lithuania": "Литва",
  "Luxembourg": "Люксембург",
  "Macao": "Макао",
  "Madagascar": "Мадагаскар",
  "Malawi": "Малави",
  "Malaysia": "Малайзия",
  "Maldives": "Мальдивы",
  "Mali": "Мали",
  "Malta": "Мальта",
  "Marshall Islands": "Маршалловы Острова",
  "Martinique": "Мартиника",
  "Mauritania": "Мавритания",
  "Mauritius": "Маврикий",
  "Mayotte": "Майотта",
  "Mexico": "Мексика",
  "Micronesia": "Микронезия",
  "Moldova": "Молдавия",
  "Monaco": "Монако",
  "Mongolia": "Монголия",
  "Montenegro": "Черногория",
  "Montserrat": "Монтсеррат",
  "Morocco": "Марокко",
  "Mozambique": "Мозамбик",
  "Myanmar": "Мьянма",
  "Namibia": "Намибия",
  "Nauru": "Науру",
  "Nepal": "Непал",
  "Netherlands": "Нидерланды",
  "New Caledonia": "Новая Каледония",
  "New Zealand": "Новая Зеландия",
  "Nicaragua": "Никарагуа",
  "Niger": "Нигер",
  "Nigeria": "Нигерия",
  "Niue": "Ниуэ",
  "Norfolk Island": "Остров Норфолк",
  "North Korea": "Северная Корея",
  "North Macedonia": "Северная Македония",
  "Northern Mariana Islands": "Северные Марианские Острова",
  "Norway": "Норвегия",
  "Oman": "Оман",
  "Pakistan": "Пакистан",
  "Palau": "Палау",
  "Palestine": "Палестина",
  "Panama": "Панама",
  "Papua New Guinea": "Папуа — Новая Гвинея",
  "Paraguay": "Парагвай",
  "Peru": "Перу",
  "Philippines": "Филиппины",
  "Pitcairn": "Острова Питкэрн",
  "Poland": "Польша",
  "Portugal": "Португалия",
  "Puerto Rico": "Пуэрто-Рико",
  "Qatar": "Катар",
  "Republic of the Congo": "Республика Конго",
  "Reunion": "Реюньон",
  "Romania": "Румыния",
  "Russia": "Россия",
  "Rwanda": "Руанда",
  "Saint Barthélemy": "Сен-Бартелеми",
  "Saint Helena": "Острова Святой Елены, Вознесения и Тристан-да-Кунья",
  "Saint Kitts and Nevis": "Сент-Китс и Невис",
  "Saint Lucia": "Сент-Люсия",
  "Saint Martin (French part)": "Сен-Мартен",
  "Saint Pierre and Miquelon": "Сен-Пьер и Микелон",
  "Saint Vincent and the Grenadines": "Сент-Винсент и Гренадины",
  "Samoa": "Самоа",
  "San Marino": "Сан-Марино",
  "Sao Tome and Principe": "Сан-Томе и Принсипи",
  "Saudi Arabia": "Саудовская Аравия",
  "Senegal": "Сенегал",
  "Serbia": "Сербия",
  "Seychelles": "Сейшельские Острова",
  "Sierra Leone": "Сьерра-Леоне",
  "Singapore": "Сингапур",
  "Sint Maarten (Dutch part)": "Синт-Мартен",
  "Slovakia": "Словакия",
  "Slovenia": "Словения",
  "Solomon Islands": "Соломоновы Острова",
  "Somalia": "Сомали",
  "South Africa": "ЮАР",
  "South Georgia and the South Sandwich Islands": "Южная Георгия и Южные Сандвичевы Острова",
  "South Korea": "Южная Корея",
  "South Sudan": "Южный Судан",
  "Spain": "Испания",
  "Sri Lanka": "Шри-Ланка",
  "Sudan": "Судан",
  "Suriname": "Суринам",
  "Svalbard and Jan Mayen": "Шпицберген и Ян-Майен",
  "Sweden": "Швеция",
  "Switzerland": "Швейцария",
  "Syria": "Сирия",
  "Taiwan": "Тайвань",
  "Tajikistan": "Таджикистан",
  "Tanzania": "Танзания",
  "Thailand": "Таиланд",
  "Timor-Leste": "Восточный Тимор",
  "Togo": "Того",
  "Tokelau": "Токелау",
  "Tonga": "Тонга",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  "Tunisia": "Тунис",
  "Turkey": "Турция",
  "Turkmenistan": "Туркмения",
  "Turks and Caicos Islands": "Теркс и Кайкос",
  "Tuvalu": "Тувалу",
  "Uganda": "Уганда",
  "Ukraine": "Украина",
  "United Arab Emirates": "ОАЭ",
  "United Kingdom": "Великобритания",
  "United States": "США",
  "United States Minor Outlying Islands": "Внешние малые острова (США)",
  "Uruguay": "Уругвай",
  "Uzbekistan": "Узбекистан",
  "Vanuatu": "Вануату",
  "Venezuela": "Венесуэла",
  "Vietnam": "Вьетнам",
  "Virgin Islands, British": "Виргинские Острова (Великобритания)",
  "Virgin Islands, U.S.": "Виргинские Острова (США)",
  "Wallis and Futuna": "Уоллис и Футуна",
  "Western Sahara": "Западная Сахара",
  "Yemen": "Йемен",
  "Zambia": "Замбия",
  "Zimbabwe": "Зимбабве",
};

// sr-Latn (черногорская латиница с иекавицей — тот же ресурс, что и cnr/Montenegrin,
// см. frontend/CLAUDE.md)
export const COUNTRY_TRANSLATIONS_SR_LATN: Record<string, string> = {
  "Afghanistan": "Avganistan",
  "Åland Islands": "Olandska Ostrva",
  "Albania": "Albanija",
  "Algeria": "Alžir",
  "American Samoa": "Američka Samoa",
  "Andorra": "Andora",
  "Angola": "Angola",
  "Anguilla": "Angvila",
  "Antarctica": "Antarktik",
  "Antigua and Barbuda": "Antigva i Barbuda",
  "Argentina": "Argentina",
  "Armenia": "Jermenija",
  "Aruba": "Aruba",
  "Australia": "Australija",
  "Austria": "Austrija",
  "Azerbaijan": "Azerbejdžan",
  "Bahamas": "Bahami",
  "Bahrain": "Bahrein",
  "Bangladesh": "Bangladeš",
  "Barbados": "Barbados",
  "Belarus": "Belorusija",
  "Belgium": "Belgija",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bermuda": "Bermuda",
  "Bhutan": "Butan",
  "Bolivia": "Bolivija",
  "Bonaire, Sint Eustatius and Saba": "Karipska Holandija",
  "Bosnia and Herzegovina": "Bosna i Hercegovina",
  "Botswana": "Bocvana",
  "Bouvet Island": "Ostrvo Buve",
  "Brazil": "Brazil",
  "British Indian Ocean Territory": "Britanska teritorija Indijskog okeana",
  "Brunei": "Brunej",
  "Bulgaria": "Bugarska",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Kambodža",
  "Cameroon": "Kamerun",
  "Canada": "Kanada",
  "Cape Verde": "Zelenortska Ostrva",
  "Cayman Islands": "Kajmanska Ostrva",
  "Central African Republic": "Centralnoafrička Republika",
  "Chad": "Čad",
  "Chile": "Čile",
  "China": "Kina",
  "Christmas Island": "Božićno Ostrvo",
  "Cocos (Keeling) Islands": "Kokosova (Kilingova) Ostrva",
  "Colombia": "Kolumbija",
  "Comoros": "Komorska Ostrva",
  "Cook Islands": "Kukova Ostrva",
  "Costa Rica": "Kostarika",
  "Cote d'Ivoire": "Obala Slonovače",
  "Croatia": "Hrvatska",
  "Cuba": "Kuba",
  "Curaçao": "Kurasao",
  "Cyprus": "Kipar",
  "Czech Republic": "Češka",
  "Democratic Republic of the Congo": "Kongo - Kinšasa",
  "Denmark": "Danska",
  "Djibouti": "Džibuti",
  "Dominica": "Dominika",
  "Dominican Republic": "Dominikanska Republika",
  "Ecuador": "Ekvador",
  "Egypt": "Egipat",
  "El Salvador": "Salvador",
  "Equatorial Guinea": "Ekvatorijalna Gvineja",
  "Eritrea": "Eritreja",
  "Estonia": "Estonija",
  "Eswatini": "Svazilend",
  "Ethiopia": "Etiopija",
  "Falkland Islands (Malvinas)": "Foklandska Ostrva",
  "Faroe Islands": "Farska Ostrva",
  "Fiji": "Fidži",
  "Finland": "Finska",
  "France": "Francuska",
  "French Guiana": "Francuska Gvajana",
  "French Polynesia": "Francuska Polinezija",
  "French Southern Territories": "Francuske Južne Teritorije",
  "Gabon": "Gabon",
  "Gambia": "Gambija",
  "Georgia": "Gruzija",
  "Germany": "Njemačka",
  "Ghana": "Gana",
  "Gibraltar": "Gibraltar",
  "Greece": "Grčka",
  "Greenland": "Grenland",
  "Grenada": "Grenada",
  "Guadeloupe": "Gvadelup",
  "Guam": "Guam",
  "Guatemala": "Gvatemala",
  "Guernsey": "Gernzi",
  "Guinea": "Gvineja",
  "Guinea-Bissau": "Gvineja-Bisao",
  "Guyana": "Gvajana",
  "Haiti": "Haiti",
  "Heard Island and McDonald Islands": "Ostrvo Herd i Mekdonaldova ostrva",
  "Holy See (Vatican City State)": "Vatikan",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hungary": "Mađarska",
  "Iceland": "Island",
  "India": "Indija",
  "Indonesia": "Indonezija",
  "Iran": "Iran",
  "Iraq": "Irak",
  "Ireland": "Irska",
  "Isle of Man": "Ostrvo Man",
  "Israel": "Izrael",
  "Italy": "Italija",
  "Jamaica": "Jamajka",
  "Japan": "Japan",
  "Jersey": "Džerzi",
  "Jordan": "Jordan",
  "Kazakhstan": "Kazahstan",
  "Kenya": "Kenija",
  "Kiribati": "Kiribati",
  "Kosovo": "Kosovo",
  "Kuwait": "Kuvajt",
  "Kyrgyzstan": "Kirgistan",
  "Laos": "Laos",
  "Latvia": "Letonija",
  "Lebanon": "Liban",
  "Lesotho": "Lesoto",
  "Liberia": "Liberija",
  "Libya": "Libija",
  "Liechtenstein": "Lihtenštajn",
  "Lithuania": "Litvanija",
  "Luxembourg": "Luksemburg",
  "Macao": "Makao",
  "Madagascar": "Madagaskar",
  "Malawi": "Malavi",
  "Malaysia": "Malezija",
  "Maldives": "Maldivi",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Islands": "Maršalska Ostrva",
  "Martinique": "Martinik",
  "Mauritania": "Mauritanija",
  "Mauritius": "Mauricijus",
  "Mayotte": "Majot",
  "Mexico": "Meksiko",
  "Micronesia": "Mikronezija",
  "Moldova": "Moldavija",
  "Monaco": "Monako",
  "Mongolia": "Mongolija",
  "Montenegro": "Crna Gora",
  "Montserrat": "Monserat",
  "Morocco": "Maroko",
  "Mozambique": "Mozambik",
  "Myanmar": "Mijanmar (Burma)",
  "Namibia": "Namibija",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Netherlands": "Holandija",
  "New Caledonia": "Nova Kaledonija",
  "New Zealand": "Novi Zeland",
  "Nicaragua": "Nikaragva",
  "Niger": "Niger",
  "Nigeria": "Nigerija",
  "Niue": "Niue",
  "Norfolk Island": "Ostrvo Norfok",
  "North Korea": "Severna Koreja",
  "North Macedonia": "Severna Makedonija",
  "Northern Mariana Islands": "Severna Marijanska Ostrva",
  "Norway": "Norveška",
  "Oman": "Oman",
  "Pakistan": "Pakistan",
  "Palau": "Palau",
  "Palestine": "Palestina",
  "Panama": "Panama",
  "Papua New Guinea": "Papua Nova Gvineja",
  "Paraguay": "Paragvaj",
  "Peru": "Peru",
  "Philippines": "Filipini",
  "Pitcairn": "Pitkern",
  "Poland": "Poljska",
  "Portugal": "Portugalija",
  "Puerto Rico": "Portoriko",
  "Qatar": "Katar",
  "Republic of the Congo": "Kongo - Brazavil",
  "Reunion": "Reinion",
  "Romania": "Rumunija",
  "Russia": "Rusija",
  "Rwanda": "Ruanda",
  "Saint Barthélemy": "Sen Bartelemi",
  "Saint Helena": "Sveta Jelena",
  "Saint Kitts and Nevis": "Sent Kits i Nevis",
  "Saint Lucia": "Sveta Lucija",
  "Saint Martin (French part)": "Sveti Martin (Francuska)",
  "Saint Pierre and Miquelon": "Sen Pjer i Mikelon",
  "Saint Vincent and the Grenadines": "Sent Vinsent i Grenadini",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "Sao Tome i Principe",
  "Saudi Arabia": "Saudijska Arabija",
  "Senegal": "Senegal",
  "Serbia": "Srbija",
  "Seychelles": "Sejšeli",
  "Sierra Leone": "Sijera Leone",
  "Singapore": "Singapur",
  "Sint Maarten (Dutch part)": "Sveti Martin (Holandija)",
  "Slovakia": "Slovačka",
  "Slovenia": "Slovenija",
  "Solomon Islands": "Solomonska Ostrva",
  "Somalia": "Somalija",
  "South Africa": "Južna Afrika",
  "South Georgia and the South Sandwich Islands": "Južna Džordžija i Južna Sendvička Ostrva",
  "South Korea": "Južna Koreja",
  "South Sudan": "Južni Sudan",
  "Spain": "Španija",
  "Sri Lanka": "Šri Lanka",
  "Sudan": "Sudan",
  "Suriname": "Surinam",
  "Svalbard and Jan Mayen": "Svalbard i Jan Majen",
  "Sweden": "Švedska",
  "Switzerland": "Švajcarska",
  "Syria": "Sirija",
  "Taiwan": "Tajvan",
  "Tajikistan": "Tadžikistan",
  "Tanzania": "Tanzanija",
  "Thailand": "Tajland",
  "Timor-Leste": "Istočni Timor",
  "Togo": "Togo",
  "Tokelau": "Tokelau",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trinidad i Tobago",
  "Tunisia": "Tunis",
  "Turkey": "Turska",
  "Turkmenistan": "Turkmenistan",
  "Turks and Caicos Islands": "Ostrva Turks i Kaikos",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Ukrajina",
  "United Arab Emirates": "UAE",
  "United Kingdom": "Ujedinjeno Kraljevstvo",
  "United States": "SAD",
  "United States Minor Outlying Islands": "Udaljena ostrva SAD",
  "Uruguay": "Urugvaj",
  "Uzbekistan": "Uzbekistan",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venecuela",
  "Vietnam": "Vijetnam",
  "Virgin Islands, British": "Britanska Devičanska Ostrva",
  "Virgin Islands, U.S.": "Američka Devičanska Ostrva",
  "Wallis and Futuna": "Valis i Futuna",
  "Western Sahara": "Zapadna Sahara",
  "Yemen": "Jemen",
  "Zambia": "Zambija",
  "Zimbabwe": "Zimbabve",
};
