// Статичные константы для Scopus-режима фильтрации.
// В каталог-режиме опции приходят из statsStore (реальные данные коллекции).

export const SCOPUS_DOC_TYPES = [
  'Article',
  'Review',
  'Conference Paper',
  'Book Chapter',
  'Editorial',
  'Letter',
  'Note',
  'Short Survey',
] as const;

export type ScopusDocType = (typeof SCOPUS_DOC_TYPES)[number];

// ~80 основных научных центров, покрывающих >95% публикаций Scopus.
// Названия соответствуют значениям AFFILCOUNTRY в CQL Scopus API.
export const SCOPUS_COUNTRIES = [
  'United States',
  'China',
  'United Kingdom',
  'Germany',
  'Japan',
  'France',
  'Italy',
  'Canada',
  'Australia',
  'South Korea',
  'India',
  'Spain',
  'Netherlands',
  'Brazil',
  'Switzerland',
  'Sweden',
  'Russia',
  'Turkey',
  'Poland',
  'Belgium',
  'Denmark',
  'Austria',
  'Norway',
  'Finland',
  'Israel',
  'Singapore',
  'Portugal',
  'Czech Republic',
  'Greece',
  'Iran',
  'Mexico',
  'Argentina',
  'South Africa',
  'New Zealand',
  'Ireland',
  'Hungary',
  'Romania',
  'Ukraine',
  'Croatia',
  'Slovakia',
  'Thailand',
  'Malaysia',
  'Indonesia',
  'Vietnam',
  'Philippines',
  'Saudi Arabia',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Ethiopia',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Taiwan',
  'Hong Kong',
  'Colombia',
  'Chile',
  'Peru',
  'Venezuela',
  'Ecuador',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Jordan',
  'Lebanon',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Ghana',
  'Tanzania',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Bulgaria',
  'Slovenia',
  'Serbia',
  'Iceland',
  'Luxembourg',
  'Malta',
  'Cyprus',
] as const;

export type ScopusCountry = (typeof SCOPUS_COUNTRIES)[number];
