name: Python tests

# События, при которых запускается CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

 # Выбираем операционную систему для виртуальной машины
jobs:
  test:
    runs-on: ubuntu-latest

# Задаем переменные окружения-заглушки для Pydantic Settings, чтобы приложение могло собраться в тестовом режиме
    env:
      SCOPUS_API_KEY: "dummy_key_for_tests"
      DB_HOST: "localhost"
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_NAME: "test_db"
      SECRET_KEY: "supersecretkey_for_ci_tests_only"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
    # 1. Скачиваем код из репозитория на виртуальную машину
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Устанавливаем Python 3.12
    - name: set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        # Кэшируем pip-пакеты для ускорения следующих прогонов
        cache: pip

    # 3. Устанавливаем зависимости из requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    # 4. Запускаем Pytest
    - name: Run Pytest
      run: |
        python -m pytest tests -vv